### ISSUE TITLE
question about training

### ISSUE THREAD

**Issue by dearkafka** [shartoo/luna16_multi_size_3dcnn#1]
It seems that as well as in paper, this implementation supposes that the nodule is in the center of the cropped cube. No shifting the center is provided. But in real life we really do not know if nodule is in center of the crop that we make from the scan, correct me if I'm wrong, but this is not directly useful for diagnosing.

**Comment by shartoo** [comment]
Yes.you're right.There is no absolute accurate coordinates,all are average values(coordinates are labeled by different radiation technologists). we'll usually do data enhancement by shifting on center  for deep learning task.

**Comment by dearkafka** [comment]
Thank you very much! Do you know any baseline, published or your own, for this kind of task on this LIDC dataset but with shifting center? I mean any usual metrics, i.e. precision, recall? I do this kind of task, mainly segmentation, achieve high dice score of 0.8-0.9, however, unstable on different batches, but sensitivity looks rather low, like 0.7

**Comment by shartoo** [comment]
Sorry,i'm not focus on lung cancer detecttion and just know  few of this kind of paper.Here is the link of papers  using [LIDC](https://wiki.cancerimagingarchive.net/display/Public/Publications#Publications-Collection:LIDC-IDRI)

**Comment by dearkafka** [comment]
Thank you for your help, forgot about this list!
